Redes neurais artificiais com keras

In [2]:
# importação das biblotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
# utilizado a biblioteca Keras por ser uma abstração sobre a biblioteca tensorflow, facilitando seu uso
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

In [3]:
#carregar dados iris
base = datasets.load_iris()
#divisão dos dados em variáveis independentes e dependentes
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
#organicar cada classe em uma coluna para atender a rede neural
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [5]:
#divisão de dados em treino e teste
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(previsores, classe_dummy, test_size= 0.3, random_state= 0)

In [6]:
#criação da estrutura da rede neural com classe Sequential
modelo = Sequential()
#primeira camada oculta, 5 neurnonios, 4 neuronio de entrada
modelo.add(Dense(units= 5, input_dim = 4)) #pode ser elevado o número de neurônios, porém os de entrada devem ser penas quatro por termos quatro informaões de entrada
#segunda camada oculta
modelo.add(Dense(units= 4))
#terceira camada oculta
#função softbox porque temos um problema de classificação com mais de duas classes
#é gerada um probabilidade em cada neunrônio
modelo.add(Dense(units= 3, activation = 'softmax'))

In [7]:
#exibir resultado de como ficou organizado a rede
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [8]:
#configuração de parâmetros da rede neural (adam = algorítmo para tualizaros pesos e Loss = cálculo de erro)
modelo.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics= ['accuracy'])
#treianmento, dividindo a base de treino em porções para validação (validation_data)
modelo.fit(x_treinamento, y_treinamento, epochs= 1000, validation_data= (x_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 1s 56ms/step - loss: 3.1972 - accuracy: 0.3714 - val_loss: 3.6747 - val_accuracy: 0.2444
Epoch 2/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.9810 - accuracy: 0.3714 - val_loss: 3.4172 - val_accuracy: 0.2444
Epoch 3/1000
4/4 [==============================] - 0s 8ms/step - loss: 2.7941 - accuracy: 0.3714 - val_loss: 3.1732 - val_accuracy: 0.2444
Epoch 4/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.6048 - accuracy: 0.3714 - val_loss: 2.9546 - val_accuracy: 0.2444
Epoch 5/1000
4/4 [==============================] - 0s 10ms/step - loss: 2.4509 - accuracy: 0.3714 - val_loss: 2.7570 - val_accuracy: 0.2444
Epoch 6/1000
4/4 [==============================] - 0s 10ms/step - loss: 2.2993 - accuracy: 0.3714 - val_loss: 2.5900 - val_accuracy: 0.2444
Epoch 7/1000
4/4 [==============================] - 0s 10ms/step - loss: 2.1826 - accuracy: 0.3714 - val_loss: 2.4467 - val_accuracy: 0.2444
Epoch 8/1000
4/4

No Epoch 1000/1000 é possível ver que o modelo com os dados de treino (accuracy) apresenta uma performance de 0.9905 e com os dados de teste (val_accuracy) 0.9778

In [9]:
#previsoes e midar a variável para True ou false de acordo com o threshold 0.5
previsoes = modelo.predict(x_teste)
previsoes = (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [11]:
#como é um problmea com três saídas, precisamos buscar a posição que possui o maior valor (são retornados três valores)
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [13]:
#geração de matrix de confusão
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)